### ISSUE TITLE
Not compiling with latest emp-toolkit/emp-tool version

### ISSUE THREAD

**Issue by fabrice102** [emp-toolkit/emp-m2pc#3]
emp-toolkit/emp-m2pc does not compile with the latest emp-toolkit/emp-tool version because of the following issues:

1. removal of the function `timeStamp` from https://github.com/emp-toolkit/emp-tool/blob/stable/utils/utils.h and https://github.com/emp-toolkit/emp-tool/blob/stable/utils/utils.hpp.
2. removal of the function `xorBlocks_arr2` from https://github.com/emp-toolkit/emp-tool/blob/stable/utils/block.h.
3. removal of the macro SERVER_IP.

For the first point, I guess the function was removed because `clock_gettime` was not supported in macOS < 10.12. The best solution might be to use `std::chrono` as in https://github.com/emp-toolkit/emp-tool/blob/master/emp-tool/utils/utils.hpp. In the later file however, the return type was changed from `double` to `uint64_t`. This might yield some issues. In the meantime, it might be simpler to keep the old implementation with `clock_gettime` and to require macOS >= 10.12.

**Comment by wangxiao1254** [comment]
xorBlocks_arr2 was removed because it was a duplication of another function, somehow..
timeStamp was remove but two new functions were added https://github.com/emp-toolkit/emp-tool/blob/stable/utils/utils.h#L56 Usage: https://github.com/emp-toolkit/emp-tool/blob/stable/test/prg.cpp#L36

I will consider add timeStamp using chrono. And take a look at double/unit64_t issue.

Thanks

**Comment by fabrice102** [comment]
I did not notice https://github.com/emp-toolkit/emp-tool/blob/stable/utils/utils.h#L56. I agree these functions are better. So maybe it's best just to convert everything to use them.

**Comment by wangxiao1254** [comment]
Changes the return type of time_from to double. This is better esp. when used to compute the average timing of a repeated experiments.
